// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6h5U84O8qWOQda6TfG7Ipi-lBqEzPvPI',
    appId: '1:793345356412:web:66f1d5441cefa6bcb94ff9',
    messagingSenderId: '793345356412',
    projectId: 'flash-chat-5533f',
    authDomain: 'flash-chat-5533f.firebaseapp.com',
    storageBucket: 'flash-chat-5533f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCESanxXgziAlLlbek5sqCNg-w79K8Eug',
    appId: '1:793345356412:android:61623f05ef915332b94ff9',
    messagingSenderId: '793345356412',
    projectId: 'flash-chat-5533f',
    storageBucket: 'flash-chat-5533f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrOuLUqHX5YAD-gZooMbPT7oSn03Vjhd0',
    appId: '1:793345356412:ios:aba6f60ed4ce3aceb94ff9',
    messagingSenderId: '793345356412',
    projectId: 'flash-chat-5533f',
    storageBucket: 'flash-chat-5533f.appspot.com',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrOuLUqHX5YAD-gZooMbPT7oSn03Vjhd0',
    appId: '1:793345356412:ios:71233841c7726634b94ff9',
    messagingSenderId: '793345356412',
    projectId: 'flash-chat-5533f',
    storageBucket: 'flash-chat-5533f.appspot.com',
    iosBundleId: 'com.example.flashChatFlutter.RunnerTests',
  );
}
